name: Create platform packager for NOTER

on:
  push:
    # Building packages is expensive (it takes about 5 minutes), so only do
    # this, if we push a version like tag.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wine
      run: |
        sudo apt-get update
        sudo apt-get install --yes wine libwine
        sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install --yes wine32
    - name: Run build
      run: |
        cd src
        npm install --include=dev
        make build
