# This is a GitHub Actions CI workflow definition
# -----------------------------------------------
#
# Builds packages with the same "make build" command that can be used locally,
# then creates a new release.
#
# Only triggered, when a tag of the form v1.2.3 will be pushed. The default
# branch "main" is checked out and built.
#
# A possible improvement: Caching dependencies; would speed up things, makes
# the workflow more complicated, see also:
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows

name: Create packages for NOTER

on:
  push:
    # Building packages is expensive (it takes about 5 minutes), so only do
    # this, if we push a version like tag.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
# https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wine
        run: |
          sudo apt-get update
          sudo apt-get install --yes wine libwine
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install --yes wine32
      - name: Run build
        run: |
          cd src
          npm install --include=dev
          make build
      - name: Checksum
        run: echo ${{ github.sha }} > noter-${{ github.ref_name }}-release.txt
      - name: Generate changelog
        run: |
          echo '# NOTER ${{ github.ref_name }}

          This is the latest release of NOTER, the simple, themable,
          llm-enhanced markdown editor.
          ' > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          # This token gets automatically populated when the workflow starts.
          # What we need it specify the permissions.
          token: ${{ github.token }}
          # This can be set to false, one we are out of our "alpha" release
          # stage.
          prerelease: false
          make_latest: true
          # Just make it so we notice, if any of the artifacts are missing.
          fail_on_unmatched_files: true
          files: |
            src/dist/noter_*_amd64.deb
            src/dist/Noter-*.AppImage
            src/dist/Noter-*-mac.zip
            src/dist/Noter-*-win.zip
            src/dist/noter-*.rpm
            release.txt
